apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-template
data:
  default.conf: |
    server {
      listen  80 default_server;
      server_name _;

      default_type text/plain;

      location / {
          return 200 '$hostname, OK, ONE MORE\n';
      }
    }
